### ISSUE TITLE
Crashes in node 0.11

### ISSUE THREAD

**Issue by ljharb** [norahiko/runsync#4]
in `node` `0.11.14`, I get the following error:

``` shell
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (./node_modules/runsync/index.js:32:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

```

It looks like this polyfill isn't actually checking for the existence of `execFileSync` etc on `child_process` .

**Comment by ljharb** [comment]
I should update add that this actually works fine when `runsync` was installed on `node 0.11` - but when it was installed on `node 0.10`, and ran on `node 0.11`, it fails.

Why would it need to be compiled on `0.11` in order to work on `0.11`?
